# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wKfpbejs3CXG4pLXV4FoxbsIYxuLG8wD
"""

import streamlit as st

def calcular_valor_esperado(chance):
    if chance <= 0:
        return "A chance deve ser maior que zero."
    else:
        valor_esperado = 1 / (chance / 100)
        return f"O valor esperado é: {valor_esperado}"

def main():
    st.title("Cálculo do Valor Esperado")
    chance = st.number_input("Informe a chance:", min_value=0.01, max_value=100.0, value=50.0, step=0.01)
    valor_esperado = calcular_valor_esperado(chance)

    st.write(valor_esperado)

if __name__ == "__main__":
    main()